# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dnsost/cpp-advanced-hse

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dnsost/cpp-advanced-hse/tasks

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dnsost/cpp-advanced-hse/tasks/CMakeFiles /home/dnsost/cpp-advanced-hse/tasks/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dnsost/cpp-advanced-hse/tasks/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named contrib_catch_main

# Build rule for target.
contrib_catch_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 contrib_catch_main
.PHONY : contrib_catch_main

# fast build rule for target.
contrib_catch_main/fast:
	$(MAKE) -f CMakeFiles/contrib_catch_main.dir/build.make CMakeFiles/contrib_catch_main.dir/build
.PHONY : contrib_catch_main/fast

#=============================================================================
# Target rules for targets named build-ctf

# Build rule for target.
build-ctf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 build-ctf
.PHONY : build-ctf

# fast build rule for target.
build-ctf/fast:
	$(MAKE) -f CMakeFiles/build-ctf.dir/build.make CMakeFiles/build-ctf.dir/build
.PHONY : build-ctf/fast

#=============================================================================
# Target rules for targets named test-all

# Build rule for target.
test-all: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-all
.PHONY : test-all

# fast build rule for target.
test-all/fast:
	$(MAKE) -f CMakeFiles/test-all.dir/build.make CMakeFiles/test-all.dir/build
.PHONY : test-all/fast

#=============================================================================
# Target rules for targets named test_multiplication

# Build rule for target.
test_multiplication: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_multiplication
.PHONY : test_multiplication

# fast build rule for target.
test_multiplication/fast:
	$(MAKE) -f tasks/multiplication/CMakeFiles/test_multiplication.dir/build.make tasks/multiplication/CMakeFiles/test_multiplication.dir/build
.PHONY : test_multiplication/fast

#=============================================================================
# Target rules for targets named test_harakiri

# Build rule for target.
test_harakiri: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_harakiri
.PHONY : test_harakiri

# fast build rule for target.
test_harakiri/fast:
	$(MAKE) -f tasks/harakiri/CMakeFiles/test_harakiri.dir/build.make tasks/harakiri/CMakeFiles/test_harakiri.dir/build
.PHONY : test_harakiri/fast

#=============================================================================
# Target rules for targets named test_deque

# Build rule for target.
test_deque: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_deque
.PHONY : test_deque

# fast build rule for target.
test_deque/fast:
	$(MAKE) -f tasks/deque/CMakeFiles/test_deque.dir/build.make tasks/deque/CMakeFiles/test_deque.dir/build
.PHONY : test_deque/fast

#=============================================================================
# Target rules for targets named test_dedup

# Build rule for target.
test_dedup: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_dedup
.PHONY : test_dedup

# fast build rule for target.
test_dedup/fast:
	$(MAKE) -f tasks/dedup/CMakeFiles/test_dedup.dir/build.make tasks/dedup/CMakeFiles/test_dedup.dir/build
.PHONY : test_dedup/fast

#=============================================================================
# Target rules for targets named test_cow_vector

# Build rule for target.
test_cow_vector: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_cow_vector
.PHONY : test_cow_vector

# fast build rule for target.
test_cow_vector/fast:
	$(MAKE) -f tasks/cow-vector/CMakeFiles/test_cow_vector.dir/build.make tasks/cow-vector/CMakeFiles/test_cow_vector.dir/build
.PHONY : test_cow_vector/fast

#=============================================================================
# Target rules for targets named test_compressed_pair

# Build rule for target.
test_compressed_pair: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_compressed_pair
.PHONY : test_compressed_pair

# fast build rule for target.
test_compressed_pair/fast:
	$(MAKE) -f tasks/compressed_pair/CMakeFiles/test_compressed_pair.dir/build.make tasks/compressed_pair/CMakeFiles/test_compressed_pair.dir/build
.PHONY : test_compressed_pair/fast

#=============================================================================
# Target rules for targets named test_lru_cache

# Build rule for target.
test_lru_cache: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_lru_cache
.PHONY : test_lru_cache

# fast build rule for target.
test_lru_cache/fast:
	$(MAKE) -f tasks/lru-cache/CMakeFiles/test_lru_cache.dir/build.make tasks/lru-cache/CMakeFiles/test_lru_cache.dir/build
.PHONY : test_lru_cache/fast

#=============================================================================
# Target rules for targets named test_string_operations

# Build rule for target.
test_string_operations: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_string_operations
.PHONY : test_string_operations

# fast build rule for target.
test_string_operations/fast:
	$(MAKE) -f tasks/string-operations/CMakeFiles/test_string_operations.dir/build.make tasks/string-operations/CMakeFiles/test_string_operations.dir/build
.PHONY : test_string_operations/fast

#=============================================================================
# Target rules for targets named test_intrusive_list

# Build rule for target.
test_intrusive_list: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_intrusive_list
.PHONY : test_intrusive_list

# fast build rule for target.
test_intrusive_list/fast:
	$(MAKE) -f tasks/intrusive-list/CMakeFiles/test_intrusive_list.dir/build.make tasks/intrusive-list/CMakeFiles/test_intrusive_list.dir/build
.PHONY : test_intrusive_list/fast

#=============================================================================
# Target rules for targets named test_list

# Build rule for target.
test_list: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_list
.PHONY : test_list

# fast build rule for target.
test_list/fast:
	$(MAKE) -f tasks/list/CMakeFiles/test_list.dir/build.make tasks/list/CMakeFiles/test_list.dir/build
.PHONY : test_list/fast

#=============================================================================
# Target rules for targets named test_string_view

# Build rule for target.
test_string_view: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_string_view
.PHONY : test_string_view

# fast build rule for target.
test_string_view/fast:
	$(MAKE) -f tasks/string-view/CMakeFiles/test_string_view.dir/build.make tasks/string-view/CMakeFiles/test_string_view.dir/build
.PHONY : test_string_view/fast

#=============================================================================
# Target rules for targets named test_bind_front

# Build rule for target.
test_bind_front: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_bind_front
.PHONY : test_bind_front

# fast build rule for target.
test_bind_front/fast:
	$(MAKE) -f tasks/bind_front/CMakeFiles/test_bind_front.dir/build.make tasks/bind_front/CMakeFiles/test_bind_front.dir/build
.PHONY : test_bind_front/fast

#=============================================================================
# Target rules for targets named test_curry

# Build rule for target.
test_curry: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_curry
.PHONY : test_curry

# fast build rule for target.
test_curry/fast:
	$(MAKE) -f tasks/curry/CMakeFiles/test_curry.dir/build.make tasks/curry/CMakeFiles/test_curry.dir/build
.PHONY : test_curry/fast

#=============================================================================
# Target rules for targets named test_stdflib

# Build rule for target.
test_stdflib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_stdflib
.PHONY : test_stdflib

# fast build rule for target.
test_stdflib/fast:
	$(MAKE) -f tasks/stdflib/CMakeFiles/test_stdflib.dir/build.make tasks/stdflib/CMakeFiles/test_stdflib.dir/build
.PHONY : test_stdflib/fast

#=============================================================================
# Target rules for targets named test_dungeon

# Build rule for target.
test_dungeon: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_dungeon
.PHONY : test_dungeon

# fast build rule for target.
test_dungeon/fast:
	$(MAKE) -f tasks/dungeon/CMakeFiles/test_dungeon.dir/build.make tasks/dungeon/CMakeFiles/test_dungeon.dir/build
.PHONY : test_dungeon/fast

#=============================================================================
# Target rules for targets named test_fold

# Build rule for target.
test_fold: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_fold
.PHONY : test_fold

# fast build rule for target.
test_fold/fast:
	$(MAKE) -f tasks/fold/CMakeFiles/test_fold.dir/build.make tasks/fold/CMakeFiles/test_fold.dir/build
.PHONY : test_fold/fast

#=============================================================================
# Target rules for targets named test_grep

# Build rule for target.
test_grep: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_grep
.PHONY : test_grep

# fast build rule for target.
test_grep/fast:
	$(MAKE) -f tasks/grep/CMakeFiles/test_grep.dir/build.make tasks/grep/CMakeFiles/test_grep.dir/build
.PHONY : test_grep/fast

#=============================================================================
# Target rules for targets named test_transform

# Build rule for target.
test_transform: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_transform
.PHONY : test_transform

# fast build rule for target.
test_transform/fast:
	$(MAKE) -f tasks/safe-transform/CMakeFiles/test_transform.dir/build.make tasks/safe-transform/CMakeFiles/test_transform.dir/build
.PHONY : test_transform/fast

#=============================================================================
# Target rules for targets named test_tryhard

# Build rule for target.
test_tryhard: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_tryhard
.PHONY : test_tryhard

# fast build rule for target.
test_tryhard/fast:
	$(MAKE) -f tasks/tryhard/CMakeFiles/test_tryhard.dir/build.make tasks/tryhard/CMakeFiles/test_tryhard.dir/build
.PHONY : test_tryhard/fast

#=============================================================================
# Target rules for targets named test_defer

# Build rule for target.
test_defer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_defer
.PHONY : test_defer

# fast build rule for target.
test_defer/fast:
	$(MAKE) -f tasks/defer/CMakeFiles/test_defer.dir/build.make tasks/defer/CMakeFiles/test_defer.dir/build
.PHONY : test_defer/fast

#=============================================================================
# Target rules for targets named test_algo_spec

# Build rule for target.
test_algo_spec: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_algo_spec
.PHONY : test_algo_spec

# fast build rule for target.
test_algo_spec/fast:
	$(MAKE) -f tasks/algo_spec/CMakeFiles/test_algo_spec.dir/build.make tasks/algo_spec/CMakeFiles/test_algo_spec.dir/build
.PHONY : test_algo_spec/fast

#=============================================================================
# Target rules for targets named test_transform_tuple

# Build rule for target.
test_transform_tuple: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_transform_tuple
.PHONY : test_transform_tuple

# fast build rule for target.
test_transform_tuple/fast:
	$(MAKE) -f tasks/transform_tuple/CMakeFiles/test_transform_tuple.dir/build.make tasks/transform_tuple/CMakeFiles/test_transform_tuple.dir/build
.PHONY : test_transform_tuple/fast

#=============================================================================
# Target rules for targets named test_reflection

# Build rule for target.
test_reflection: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_reflection
.PHONY : test_reflection

# fast build rule for target.
test_reflection/fast:
	$(MAKE) -f tasks/reflection/CMakeFiles/test_reflection.dir/build.make tasks/reflection/CMakeFiles/test_reflection.dir/build
.PHONY : test_reflection/fast

#=============================================================================
# Target rules for targets named test_pipes

# Build rule for target.
test_pipes: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_pipes
.PHONY : test_pipes

# fast build rule for target.
test_pipes/fast:
	$(MAKE) -f tasks/pipes/CMakeFiles/test_pipes.dir/build.make tasks/pipes/CMakeFiles/test_pipes.dir/build
.PHONY : test_pipes/fast

#=============================================================================
# Target rules for targets named test_shared_from_this

# Build rule for target.
test_shared_from_this: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_shared_from_this
.PHONY : test_shared_from_this

# fast build rule for target.
test_shared_from_this/fast:
	$(MAKE) -f tasks/smart-ptrs/CMakeFiles/test_shared_from_this.dir/build.make tasks/smart-ptrs/CMakeFiles/test_shared_from_this.dir/build
.PHONY : test_shared_from_this/fast

#=============================================================================
# Target rules for targets named test_shared_weak

# Build rule for target.
test_shared_weak: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_shared_weak
.PHONY : test_shared_weak

# fast build rule for target.
test_shared_weak/fast:
	$(MAKE) -f tasks/smart-ptrs/CMakeFiles/test_shared_weak.dir/build.make tasks/smart-ptrs/CMakeFiles/test_shared_weak.dir/build
.PHONY : test_shared_weak/fast

#=============================================================================
# Target rules for targets named test_shared_basic

# Build rule for target.
test_shared_basic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_shared_basic
.PHONY : test_shared_basic

# fast build rule for target.
test_shared_basic/fast:
	$(MAKE) -f tasks/smart-ptrs/CMakeFiles/test_shared_basic.dir/build.make tasks/smart-ptrs/CMakeFiles/test_shared_basic.dir/build
.PHONY : test_shared_basic/fast

#=============================================================================
# Target rules for targets named test_unique_advanced

# Build rule for target.
test_unique_advanced: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_unique_advanced
.PHONY : test_unique_advanced

# fast build rule for target.
test_unique_advanced/fast:
	$(MAKE) -f tasks/smart-ptrs/CMakeFiles/test_unique_advanced.dir/build.make tasks/smart-ptrs/CMakeFiles/test_unique_advanced.dir/build
.PHONY : test_unique_advanced/fast

#=============================================================================
# Target rules for targets named test_unique_basic

# Build rule for target.
test_unique_basic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_unique_basic
.PHONY : test_unique_basic

# fast build rule for target.
test_unique_basic/fast:
	$(MAKE) -f tasks/smart-ptrs/CMakeFiles/test_unique_basic.dir/build.make tasks/smart-ptrs/CMakeFiles/test_unique_basic.dir/build
.PHONY : test_unique_basic/fast

#=============================================================================
# Target rules for targets named test_brainfuck

# Build rule for target.
test_brainfuck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_brainfuck
.PHONY : test_brainfuck

# fast build rule for target.
test_brainfuck/fast:
	$(MAKE) -f tasks/brainfuck/CMakeFiles/test_brainfuck.dir/build.make tasks/brainfuck/CMakeFiles/test_brainfuck.dir/build
.PHONY : test_brainfuck/fast

#=============================================================================
# Target rules for targets named test_solve_or_die

# Build rule for target.
test_solve_or_die: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_solve_or_die
.PHONY : test_solve_or_die

# fast build rule for target.
test_solve_or_die/fast:
	$(MAKE) -f tasks/solve_or_die/CMakeFiles/test_solve_or_die.dir/build.make tasks/solve_or_die/CMakeFiles/test_solve_or_die.dir/build
.PHONY : test_solve_or_die/fast

#=============================================================================
# Target rules for targets named ctf_gcd

# Build rule for target.
ctf_gcd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ctf_gcd
.PHONY : ctf_gcd

# fast build rule for target.
ctf_gcd/fast:
	$(MAKE) -f tasks/gcd/CMakeFiles/ctf_gcd.dir/build.make tasks/gcd/CMakeFiles/ctf_gcd.dir/build
.PHONY : ctf_gcd/fast

#=============================================================================
# Target rules for targets named ctf_rule_of_5

# Build rule for target.
ctf_rule_of_5: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ctf_rule_of_5
.PHONY : ctf_rule_of_5

# fast build rule for target.
ctf_rule_of_5/fast:
	$(MAKE) -f tasks/rule-of-5/CMakeFiles/ctf_rule_of_5.dir/build.make tasks/rule-of-5/CMakeFiles/ctf_rule_of_5.dir/build
.PHONY : ctf_rule_of_5/fast

#=============================================================================
# Target rules for targets named ctf_reallol

# Build rule for target.
ctf_reallol: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ctf_reallol
.PHONY : ctf_reallol

# fast build rule for target.
ctf_reallol/fast:
	$(MAKE) -f tasks/reallol/CMakeFiles/ctf_reallol.dir/build.make tasks/reallol/CMakeFiles/ctf_reallol.dir/build
.PHONY : ctf_reallol/fast

#=============================================================================
# Target rules for targets named ctf_bad_hash

# Build rule for target.
ctf_bad_hash: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ctf_bad_hash
.PHONY : ctf_bad_hash

# fast build rule for target.
ctf_bad_hash/fast:
	$(MAKE) -f tasks/bad-hash/CMakeFiles/ctf_bad_hash.dir/build.make tasks/bad-hash/CMakeFiles/ctf_bad_hash.dir/build
.PHONY : ctf_bad_hash/fast

contrib/catch/catch_main.o: contrib/catch/catch_main.cpp.o

.PHONY : contrib/catch/catch_main.o

# target to build an object file
contrib/catch/catch_main.cpp.o:
	$(MAKE) -f CMakeFiles/contrib_catch_main.dir/build.make CMakeFiles/contrib_catch_main.dir/contrib/catch/catch_main.cpp.o
.PHONY : contrib/catch/catch_main.cpp.o

contrib/catch/catch_main.i: contrib/catch/catch_main.cpp.i

.PHONY : contrib/catch/catch_main.i

# target to preprocess a source file
contrib/catch/catch_main.cpp.i:
	$(MAKE) -f CMakeFiles/contrib_catch_main.dir/build.make CMakeFiles/contrib_catch_main.dir/contrib/catch/catch_main.cpp.i
.PHONY : contrib/catch/catch_main.cpp.i

contrib/catch/catch_main.s: contrib/catch/catch_main.cpp.s

.PHONY : contrib/catch/catch_main.s

# target to generate assembly for a file
contrib/catch/catch_main.cpp.s:
	$(MAKE) -f CMakeFiles/contrib_catch_main.dir/build.make CMakeFiles/contrib_catch_main.dir/contrib/catch/catch_main.cpp.s
.PHONY : contrib/catch/catch_main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... contrib_catch_main"
	@echo "... build-ctf"
	@echo "... rebuild_cache"
	@echo "... test-all"
	@echo "... test_multiplication"
	@echo "... test_harakiri"
	@echo "... test_deque"
	@echo "... test_dedup"
	@echo "... test_cow_vector"
	@echo "... test_compressed_pair"
	@echo "... test_lru_cache"
	@echo "... test_string_operations"
	@echo "... test_intrusive_list"
	@echo "... test_list"
	@echo "... test_string_view"
	@echo "... test_bind_front"
	@echo "... test_curry"
	@echo "... test_stdflib"
	@echo "... test_dungeon"
	@echo "... test_fold"
	@echo "... test_grep"
	@echo "... test_transform"
	@echo "... test_tryhard"
	@echo "... test_defer"
	@echo "... test_algo_spec"
	@echo "... test_transform_tuple"
	@echo "... test_reflection"
	@echo "... test_pipes"
	@echo "... test_shared_from_this"
	@echo "... test_shared_weak"
	@echo "... test_shared_basic"
	@echo "... test_unique_advanced"
	@echo "... test_unique_basic"
	@echo "... test_brainfuck"
	@echo "... test_solve_or_die"
	@echo "... ctf_gcd"
	@echo "... ctf_rule_of_5"
	@echo "... ctf_reallol"
	@echo "... ctf_bad_hash"
	@echo "... contrib/catch/catch_main.o"
	@echo "... contrib/catch/catch_main.i"
	@echo "... contrib/catch/catch_main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

